name: my_professionals_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.0-99.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    



    
  cupertino_icons: ^1.0.4
  animated_text_kit: ^4.2.2
  google_fonts: ^6.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  google_nav_bar: ^5.0.6
  curved_navigation_bar: ^1.0.3
  cloud_firestore: ^4.15.4
  url_launcher: ^6.2.4
  shimmer: ^3.0.0
  shimmer_effect: ^1.0.4
  google_sign_in: ^6.2.1
  google_maps_flutter: ^2.6.0
  sign_in_button: ^3.2.0
  flutter_rating_bar: ^4.0.1
  image_picker:  ^0.8.4+2 
  flutter_map: ^6.1.0
  webview_flutter: ^2.0.0
  flutter_motion: ^0.0.3
  motion: ^1.4.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/google.png
